site_name: Panentheon
repo_url: https://github.com/openartist/panentheon
edit_uri: edit/main/docs/
theme:
  name: material
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - content.action.edit
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  palette:
    - scheme: default
      primary: white
      accent: black
  copyright: Copyright &copy; Panentheon
  extra:
    generator: false

extra_css:
  - assets/stylesheets/extra.css

extra:
  generator: false

nav:
  - Home: index.md
  - History: history.md
  - About: about.md
  - Glossary:
    - Apeiron: glossary/apeiron.md
    - Eudaimonia: glossary/eudaimonia.md
  - Contributor Guide: contributor_guide.md